### PR TITLE
Add right turn scenario for VRU collision

### PR DESCRIPTION
**Pull request by MishkaMN**
# PR Details
## Description

As we get closer to verification testing, we need a scenario where permissive right turn results in vru collision. This scenario is described in Intersection Safety Challenge project. 
- So in XML file, I added a pedestrian and a road-side equipment such that the right turn can collide with the pedestrian

The tester still only need to modify the Python file to change the pedestrian's speed and its trigger distance from the vehicle to start walking. 

## Related Issue
CDAR-731
https://usdot-carma.atlassian.net/browse/CDAR-731

Related PR: https://github.com/usdot-fhwa-stol/carma-config/pull/313

## Motivation and Context
VRU use case verification testing

## How Has This Been Tested?
Sim PC 1

## Types of changes

- [ ] Defect fix (non-breaking change that fixes an issue)
- [X] New feature (non-breaking change that adds functionality)
- [ ] Breaking change (fix or feature that cause existing functionality to change)

## Checklist:

- [X] I have added any new packages to the sonar-scanner.properties file
- [ ] My change requires a change to the documentation.
- [X] I have updated the documentation accordingly.
- [X] I have read the **CONTRIBUTING** document.
[CDA Telematics Contributing Guide](https://github.com/usdot-fhwa-stol/cda-telematics/blob/main/Contributing.md) 
- [X] I have added tests to cover my changes.
- [X] All new and existing tests passed.

### CODE REVIEW

**Review by adamlm — CHANGES_REQUESTED** [review]
This is going to break the existing `Trb2024` scenario definition. We should add a new `VulnerableRoadUserCollision` scenario definition alongside the existing scenario.

**Comment by MishkaMN** [comment]
> This is going to break the existing `Trb2024` scenario definition. We should add a new `VulnerableRoadUserCollision` scenario definition alongside the existing scenario.

I added back the Trb2024 scenario files

**Review by adamlm — APPROVED** [review]

**Comment by MishkaMN** [comment]
In order to avoid duplicate work and potential divergence of implementation. I am closing this PR and tracking the scenario in carma-config. Currently we need all the config in carma-config to run the scenario successfully anyways, so I am okay only tracking it there.

**Comment by adamlm** [comment]
Superseded by usdot-fhwa-stol/carma-config#313

**Pull request closed without merging**
